version: "3.8"

services:
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 81:3000

  backend:
    depends_on:
      - dbh
      - dba
    build: ./backend
    ports:
      - 3001:3001
    command: ./docker-entrypoint.sh

  dbh:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vol1:/data/db

  dba:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017
    volumes:
      - vol2:/data/db

volumes:
  vol2:
    driver: local
  vol1:
    driver: local
